GET http://localhost:8888/

###
GET http://localhost:8888/login

###
POST http://localhost:8888/register
Content-Type: application/json

{
  "name": "no name",
  "email": "admin@mailcom",
  "password": "admin#123"
}

###

POST http://localhost:8888/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin#123"
}

###
GET http://localhost:8888/users/1

###
PUT http://localhost:8888/users/1
Content-Type: application/json

{
  "email": "euy@mail.com",
  "password": "admin#123"
}

###

DELETE http://localhost:8888/users/1